spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/rating-service # Combine the URI and database
  application:
    name: rating-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true